title: Begrippenkader | Netbeheer Nederland
theme: just-the-docs
baseurl: /begrippen

defaults:
  - scope:
      path: ""
    values:
      layout: default

color_scheme: nbnl
logo: "/assets/images/logo.svg"
fav_icon: "/assets/images/favicon.png"

callouts:
  note:
    color: purple

aux_links:
  "Modellen van Netbeheer Nederland":
    - "/"

plugins:
  - jekyll-redirect-from

collections:
  doc:
    output: true

just_the_docs:
  collections:
    doc:
      name: Begrippen

search:
  heading_level: 1
  